---
title: "XX: Tara Ocean 16s OTU"
author: "Shane"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(ggridges)
library(patchwork)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



# Data import

```{r}
data = read_csv("data/site_phylum_pct.csv")

location = 
  read_excel(
    "data/OM.CompanionTables.xlsx", 
    sheet = 2, 
    col_names=TRUE
  ) %>% 
  janitor::clean_names() %>% 
  mutate(
    site = sample_label_tara_station_number_environmental_feature_size_fraction,
    location = ocean_and_sea_regions_iho_general_sea_areas_1953_mrgid_registered_at_www_marineregions_com
  ) %>% 
  select(site, location)
  
  
```




