---
title: "Data Analysis: Tara Ocean 16s OTU"
author: "Shane"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



## Data import

```{r}
otu = read_tsv("data/miTAG.taxonomic.profiles.release.tsv") %>% 
  janitor::clean_names()
```



## Tidy

```{r}
otu_tidy = otu %>% 
  pivot_longer(
    starts_with("tara_"),
    names_to = "site",
    values_to = "count",
    values_drop_na = TRUE,
  )
```

``` {r}
otu_site = otu_tidy %>% 
  select("site", "phylum", "count") %>% 
  arrange(site, phylum)
```



## Basic plotly

```{}
type_count_plotly = function(x) {
  
  count_plotly = otu_tidy %>% 
  filter(otu.rep == x) %>% 
  mutate(type =fct_reorder(site, count)) %>% 
  plot_ly(x = ~site, y = ~count, color = ~site, type = "bar", colors = "viridis")
  
  count_plotly
  
}

type_count_plotly("AACY024102418.157.1623")

output = map(.x = otu_nest, ~ type_count_plotly(.x))
```




## Cumulative histogram
```{}
ggplot(data=otu_site, aes(x=phylum, group=site, fill=site)) +
  geom_density(adjust=1.5, position="fill") +
  theme(axis.text.x = element_text(angle = 270, hjust = 1), legend.position = "none")
```

```{r}
otu_sum = 
  otu_site %>%
  group_by(site, phylum) %>%
  summarise(sum = sum(count)) 
```

```{}
ggplot(data = otu_sum, aes(x=site, group=phylum, fill=phylum)) +
  geom_density(adjust=1.5, position="fill") +
  theme(axis.text.x = element_text(angle = 270, hjust = 1))
```

```{}
prct = function(x) {
  
  prct = round(x / sum(x), 10)
  
  tibble(
    count = x, 
    prct = prct
  )
}

otu_prct = data.frame(otu_sum[1:2], lapply(otu_sum[3], prct) )

otu_prct %>% 
  select(-count.count, -phylum) %>% 
  group_by(site) %>% 
  summarise_each(funs(sum))

otu_prct %>% filter(site == "tara_023_dcm_0_22_1_6")
```


``` {}
ots_nest = otu_sum %>% 
  select(-phylum) %>% 
  nest(data = count)

output = map(ots_nest$data, prct)
```

```{r}
order = otu_sum %>% select("site") %>% unique() %>% tibble::rowid_to_column("order") %>% as_tibble()

ots_order = left_join(order, otu_sum, by = "site")
```

```{r}
pct = function(x) {
  
  pct = otu_sum %>% 
  filter(site == x) %>% 
  mutate(
    pct = round(count / sum(count), 5)
  )
  
  tibble((pct))
}

pct("tara_004_srf_0_22_1_6")
```

```{r}
output = vector("list", length = 7784)

for (i in 1:7784) {
  output[[i]] = pct(otu_sum$site[[i]])
}


output_df = bind_rows(output) %>% unique()

output_df %>% 
  select(-count, -phylum) %>% 
  group_by(site) %>% 
  summarise_each(funs(sum))
```

```{r}
plot = ggplot(output_df, aes(x=site, y=pct, fill=phylum)) + 
  geom_col(position = 'stack', width = 0.6) +
  theme(axis.text.x = element_text(angle = 270, hjust = 1), legend.position = "right")

ggplotly(plot)
```



